project:
  type: website
  output-dir: docs
  render:
    - "*.qmd"
    - "!*.Rmd"
  resources:
    - files/*.Rmd
    - files/*.html
    
website:
  title: "PPN"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - syllabus.qmd
      - modules/index.qmd
      - datasets/index.qmd
      - resources.qmd
      - exercises.qmd
    tools:
      - icon: github
        menu:
          - text: Source Code
            href:  https://github.com/ritcheym/ppn
  back-to-top-navigation: false
  page-footer: "Last updated April 2025."
    
  sidebar:
    style: "floating"
    search: true
    contents:
      - section: "<b>Modules</b>"
        href: modules/index.qmd
        contents:
          - text: "<mark>Intro to Programming</mark>"
          - modules/01_intro.qmd
          - modules/02_programming-foundations-1.qmd
          - modules/03_programming-foundations-2.qmd
          - modules/04_programming-workshop.qmd
          - text: "<mark>Data Manipulation</mark>"
          - modules/05_data-visualization.qmd
          - modules/06_data-summaries.qmd
          - modules/07_data-wrangling.qmd
          - modules/08_data-relations.qmd
          - modules/09_data-tidying.qmd
          - text: "<mark>Data Analysis</mark>"
          - modules/10_statistical-analysis.qmd
          - modules/11_machine-learning.qmd
          - text: "<mark>Additional Topics</mark>"
          - modules/11_nlp.qmd
          - modules/12_advanced-visualization.qmd
          - modules/xx_intro-jspsych.qmd
          - modules/xx_experiment-design.qmd
      - section: "<b>Projects</b>"
        contents:
          - projects/midterm-project.qmd
          - projects/final-project.qmd
          - projects

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true

editor: visual

